In [2]:
# התקנת הספריות הנדרשות
!pip install -q transformers datasets evaluate accelerate scikit-learn kaggle

import os
import shutil
import torch
import evaluate
import numpy as np
from datasets import load_dataset
from transformers import AutoImageProcessor, ViTForImageClassification, TrainingArguments, Trainer
from google.colab import userdata
from huggingface_hub import login, HfApi

# משיכת מפתחות הגישה מתוך הסודות של קולאב
os.environ['KAGGLE_USERNAME'] = userdata.get('KAGGLE_USERNAME')
os.environ['KAGGLE_KEY'] = userdata.get('KAGGLE_KEY')

print("מוריד את דטאסט FreshCheck הרשמי מקאגל...")
!kaggle datasets download -d orofinadedamola/freshcheck-fruit-ripeness-classification-dataset

print("מחלץ את הנתונים...")
!unzip -q -o freshcheck-fruit-ripeness-classification-dataset.zip -d freshcheck_data/

print("סורק את התיקיות ומסדר את תמונות העגבנייה...")
source_dir = "freshcheck_data"
target_dir = "clean_tomato_dataset"

if os.path.exists(target_dir):
    shutil.rmtree(target_dir)

image_count = 0
for root, dirs, files in os.walk(source_dir):
    for file in files:
        if file.lower().endswith(('.png', '.jpg', '.jpeg')):
            full_path = root.lower()

            # מוודאים שמדובר בעגבנייה
            if 'tomato' in full_path or 'tomato' in file.lower():
                class_name = None

                # סדר הבדיקה חשוב כדי לא להתבלבל בין המילים השונות
                if 'overripe' in full_path:
                    class_name = 'overripe'
                elif 'unripe' in full_path:
                    class_name = 'unripe'
                elif 'rotten' in full_path or 'damaged' in full_path:
                    class_name = 'damaged'
                elif 'ripe' in full_path:
                    class_name = 'ripe'

                if class_name:
                    class_dir = os.path.join(target_dir, class_name)
                    os.makedirs(class_dir, exist_ok=True)
                    # יצירת שם ייחודי כדי למנוע דריסת קבצים
                    new_file_name = f"{image_count}_{file}"
                    shutil.copy(os.path.join(root, file), os.path.join(class_dir, new_file_name))
                    image_count += 1

print(f"נמצאו וסודרו בהצלחה {image_count} תמונות.")

print("טוען את התמונות למבנה נתונים...")
dataset = load_dataset("imagefolder", data_dir=target_dir)

# חלוקה מחדש לאימון, ולידציה ובדיקה
splits = dataset['train'].train_test_split(test_size=0.2, seed=42)
train_ds = splits['train']
val_test_splits = splits['test'].train_test_split(test_size=0.5, seed=42)
val_ds = val_test_splits['train']
test_ds = val_test_splits['test']

label_names = train_ds.features['label'].names
id2label = {i: name for i, name in enumerate(label_names)}
label2id = {name: i for i, name in enumerate(label_names)}

print(f"המחלקות שזוהו בהצלחה: {label_names}")

# עיבוד מקדים לתמונות
model_name = "google/vit-base-patch16-224"
processor = AutoImageProcessor.from_pretrained(model_name)

def transforms(examples):
    inputs = processor([img.convert("RGB") for img in examples["image"]], return_tensors="pt")
    inputs["labels"] = examples["label"]
    return inputs

train_ds.set_transform(transforms)
val_ds.set_transform(transforms)
test_ds.set_transform(transforms)

# הגדרת המודל
model = ViTForImageClassification.from_pretrained(
    model_name,
    num_labels=len(label_names),
    id2label=id2label,
    label2id=label2id,
    ignore_mismatched_sizes=True
)

metric = evaluate.load("accuracy")

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)
    return metric.compute(predictions=predictions, references=labels)

def collate_fn(batch):
    return {
        'pixel_values': torch.stack([x['pixel_values'] for x in batch]),
        'labels': torch.tensor([x['labels'] for x in batch])
    }

training_args = TrainingArguments(
    output_dir="./tomadoc_advanced_ripeness",
    per_device_train_batch_size=32,
    per_device_eval_batch_size=32,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="epoch",
    num_train_epochs=5,
    fp16=True,
    learning_rate=2e-5,
    save_total_limit=2,
    remove_unused_columns=False,
    load_best_model_at_end=True,
    metric_for_best_model="accuracy"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    processing_class=processor,
    compute_metrics=compute_metrics,
    data_collator=collate_fn
)

print("מתחיל אימון למודל הבשלות המתקדם...")
trainer.train()

print("מעריך ביצועים על נתוני הבדיקה...")
test_results = trainer.evaluate(test_ds)
accuracy_score = test_results.get('eval_accuracy', 0.0)
print(f"דיוק סופי: {accuracy_score:.4f}")

print("התהליך הושלם בהצלחה.")

מוריד את דטאסט FreshCheck הרשמי מקאגל...
Dataset URL: https://www.kaggle.com/datasets/orofinadedamola/freshcheck-fruit-ripeness-classification-dataset
License(s): CC-BY-SA-4.0
freshcheck-fruit-ripeness-classification-dataset.zip: Skipping, found more recently modified local copy (use --force to force download)
מחלץ את הנתונים...
סורק את התיקיות ומסדר את תמונות העגבנייה...
נמצאו וסודרו בהצלחה 7224 תמונות.
טוען את התמונות למבנה נתונים...

Resolving data files:   0%|          | 0/5779 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/721 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/724 [00:00<?, ?it/s]

Downloading data:   0%|          | 0/5779 [00:00<?, ?files/s]

Downloading data:   0%|          | 0/721 [00:00<?, ?files/s]

Downloading data:   0%|          | 0/724 [00:00<?, ?files/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

המחלקות שזוהו בהצלחה: ['damaged', 'overripe', 'ripe', 'unripe']

preprocessor_config.json:   0%|          | 0.00/160 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/69.7k [00:00<?, ?B/s]

[transformers] You passed `num_labels=4` which is incompatible to the `id2label` map of length `1000`.

model.safetensors:   0%|          | 0.00/346M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

[transformers] ViTForImageClassification LOAD REPORT from: google/vit-base-patch16-224
Key               | Status   |
------------------+----------+------------------------------------------------------------------------------------------
classifier.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([1000]) vs model:torch.Size([4])
classifier.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([1000, 768]) vs model:torch.Size([4, 768])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

Downloading builder script: 0.00B [00:00, ?B/s]

מתחיל אימון למודל הבשלות המתקדם...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['vit.layers.0.attention.q_proj.weight', 'vit.layers.0.attention.q_proj.bias', 'vit.layers.0.attention.k_proj.weight', 'vit.layers.0.attention.k_proj.bias', 'vit.layers.0.attention.v_proj.weight', 'vit.layers.0.attention.v_proj.bias', 'vit.layers.0.attention.o_proj.weight', 'vit.layers.0.attention.o_proj.bias', 'vit.layers.0.layernorm_before.weight', 'vit.layers.0.layernorm_before.bias', 'vit.layers.0.layernorm_after.weight', 'vit.layers.0.layernorm_after.bias', 'vit.layers.0.mlp.fc1.weight', 'vit.layers.0.mlp.fc1.bias', 'vit.layers.0.mlp.fc2.weight', 'vit.layers.0.mlp.fc2.bias', 'vit.layers.1.attention.q_proj.weight', 'vit.layers.1.attention.q_proj.bias', 'vit.layers.1.attention.k_proj.weight', 'vit.layers.1.attention.k_proj.bias', 'vit.layers.1.attention.v_proj.weight', 'vit.layers.1.attention.v_proj.bias', 'vit.layers.1.attention.o_proj.weight', 'vit.layers.1.attention.o_proj.bias', 'vit.layers.1.layernorm_before.weight', 'vit.layers.1.layernorm_before.bias', 'vit.layers.1.layernorm_after.weight', 'vit.layers.1.layernorm_after.bias', 'vit.layers.1.mlp.fc1.weight', 'vit.layers.1.mlp.fc1.bias', 'vit.layers.1.mlp.fc2.weight', 'vit.layers.1.mlp.fc2.bias', 'vit.layers.2.attention.q_proj.weight', 'vit.layers.2.attention.q_proj.bias', 'vit.layers.2.attention.k_proj.weight', 'vit.layers.2.attention.k_proj.bias', 'vit.layers.2.attention.v_proj.weight', 'vit.layers.2.attention.v_proj.bias', 'vit.layers.2.attention.o_proj.weight', 'vit.layers.2.attention.o_proj.bias', 'vit.layers.2.layernorm_before.weight', 'vit.layers.2.layernorm_before.bias', 'vit.layers.2.layernorm_after.weight', 'vit.layers.2.layernorm_after.bias', 'vit.layers.2.mlp.fc1.weight', 'vit.layers.2.mlp.fc1.bias', 'vit.layers.2.mlp.fc2.weight', 'vit.layers.2.mlp.fc2.bias', 'vit.layers.3.attention.q_proj.weight', 'vit.layers.3.attention.q_proj.bias', 'vit.layers.3.attention.k_proj.weight', 'vit.layers.3.attention.k_proj.bias', 'vit.layers.3.attention.v_proj.weight', 'vit.layers.3.attention.v_proj.bias', 'vit.layers.3.attention.o_proj.weight', 'vit.layers.3.attention.o_proj.bias', 'vit.layers.3.layernorm_before.weight', 'vit.layers.3.layernorm_before.bias', 'vit.layers.3.layernorm_after.weight', 'vit.layers.3.layernorm_after.bias', 'vit.layers.3.mlp.fc1.weight', 'vit.layers.3.mlp.fc1.bias', 'vit.layers.3.mlp.fc2.weight', 'vit.layers.3.mlp.fc2.bias', 'vit.layers.4.attention.q_proj.weight', 'vit.layers.4.attention.q_proj.bias', 'vit.layers.4.attention.k_proj.weight', 'vit.layers.4.attention.k_proj.bias', 'vit.layers.4.attention.v_proj.weight', 'vit.layers.4.attention.v_proj.bias', 'vit.layers.4.attention.o_proj.weight', 'vit.layers.4.attention.o_proj.bias', 'vit.layers.4.layernorm_before.weight', 'vit.layers.4.layernorm_before.bias', 'vit.layers.4.layernorm_after.weight', 'vit.layers.4.layernorm_after.bias', 'vit.layers.4.mlp.fc1.weight', 'vit.layers.4.mlp.fc1.bias', 'vit.layers.4.mlp.fc2.weight', 'vit.layers.4.mlp.fc2.bias', 'vit.layers.5.attention.q_proj.weight', 'vit.layers.5.attention.q_proj.bias', 'vit.layers.5.attention.k_proj.weight', 'vit.layers.5.attention.k_proj.bias', 'vit.layers.5.attention.v_proj.weight', 'vit.layers.5.attention.v_proj.bias', 'vit.layers.5.attention.o_proj.weight', 'vit.layers.5.attention.o_proj.bias', 'vit.layers.5.layernorm_before.weight', 'vit.layers.5.layernorm_before.bias', 'vit.layers.5.layernorm_after.weight', 'vit.layers.5.layernorm_after.bias', 'vit.layers.5.mlp.fc1.weight', 'vit.layers.5.mlp.fc1.bias', 'vit.layers.5.mlp.fc2.weight', 'vit.layers.5.mlp.fc2.bias', 'vit.layers.6.attention.q_proj.weight', 'vit.layers.6.attention.q_proj.bias', 'vit.layers.6.attention.k_proj.weight', 'vit.layers.6.attention.k_proj.bias', 'vit.layers.6.attention.v_proj.weight', 'vit.layers.6.attention.v_proj.bias', 'vit.layers.6.attention.o_proj.weight', 'vit.layers.6.attention.o_proj.bias', 'vit.layers.6.layernorm_before.weight', 'vit.layers.6.layernorm_before.bias', 'vit.layers.6.layernorm_after.weight', 'vit.layers.6.layernorm_after.bias', 'vit.layers.6.mlp.fc1.weight', 'vit.layers.6.mlp.fc1.bias', 'vit.layers.6.mlp.fc2.weight', 'vit.layers.6.mlp.fc2.bias', 'vit.layers.7.attention.q_proj.weight', 'vit.layers.7.attention.q_proj.bias', 'vit.layers.7.attention.k_proj.weight', 'vit.layers.7.attention.k_proj.bias', 'vit.layers.7.attention.v_proj.weight', 'vit.layers.7.attention.v_proj.bias', 'vit.layers.7.attention.o_proj.weight', 'vit.layers.7.attention.o_proj.bias', 'vit.layers.7.layernorm_before.weight', 'vit.layers.7.layernorm_before.bias', 'vit.layers.7.layernorm_after.weight', 'vit.layers.7.layernorm_after.bias', 'vit.layers.7.mlp.fc1.weight', 'vit.layers.7.mlp.fc1.bias', 'vit.layers.7.mlp.fc2.weight', 'vit.layers.7.mlp.fc2.bias', 'vit.layers.8.attention.q_proj.weight', 'vit.layers.8.attention.q_proj.bias', 'vit.layers.8.attention.k_proj.weight', 'vit.layers.8.attention.k_proj.bias', 'vit.layers.8.attention.v_proj.weight', 'vit.layers.8.attention.v_proj.bias', 'vit.layers.8.attention.o_proj.weight', 'vit.layers.8.attention.o_proj.bias', 'vit.layers.8.layernorm_before.weight', 'vit.layers.8.layernorm_before.bias', 'vit.layers.8.layernorm_after.weight', 'vit.layers.8.layernorm_after.bias', 'vit.layers.8.mlp.fc1.weight', 'vit.layers.8.mlp.fc1.bias', 'vit.layers.8.mlp.fc2.weight', 'vit.layers.8.mlp.fc2.bias', 'vit.layers.9.attention.q_proj.weight', 'vit.layers.9.attention.q_proj.bias', 'vit.layers.9.attention.k_proj.weight', 'vit.layers.9.attention.k_proj.bias', 'vit.layers.9.attention.v_proj.weight', 'vit.layers.9.attention.v_proj.bias', 'vit.layers.9.attention.o_proj.weight', 'vit.layers.9.attention.o_proj.bias', 'vit.layers.9.layernorm_before.weight', 'vit.layers.9.layernorm_before.bias', 'vit.layers.9.layernorm_after.weight', 'vit.layers.9.layernorm_after.bias', 'vit.layers.9.mlp.fc1.weight', 'vit.layers.9.mlp.fc1.bias', 'vit.layers.9.mlp.fc2.weight', 'vit.layers.9.mlp.fc2.bias', 'vit.layers.10.attention.q_proj.weight', 'vit.layers.10.attention.q_proj.bias', 'vit.layers.10.attention.k_proj.weight', 'vit.layers.10.attention.k_proj.bias', 'vit.layers.10.attention.v_proj.weight', 'vit.layers.10.attention.v_proj.bias', 'vit.layers.10.attention.o_proj.weight', 'vit.layers.10.attention.o_proj.bias', 'vit.layers.10.layernorm_before.weight', 'vit.layers.10.layernorm_before.bias', 'vit.layers.10.layernorm_after.weight', 'vit.layers.10.layernorm_after.bias', 'vit.layers.10.mlp.fc1.weight', 'vit.layers.10.mlp.fc1.bias', 'vit.layers.10.mlp.fc2.weight', 'vit.layers.10.mlp.fc2.bias', 'vit.layers.11.attention.q_proj.weight', 'vit.layers.11.attention.q_proj.bias', 'vit.layers.11.attention.k_proj.weight', 'vit.layers.11.attention.k_proj.bias', 'vit.layers.11.attention.v_proj.weight', 'vit.layers.11.attention.v_proj.bias', 'vit.layers.11.attention.o_proj.weight', 'vit.layers.11.attention.o_proj.bias', 'vit.layers.11.layernorm_before.weight', 'vit.layers.11.layernorm_before.bias', 'vit.layers.11.layernorm_after.weight', 'vit.layers.11.layernorm_after.bias', 'vit.layers.11.mlp.fc1.weight', 'vit.layers.11.mlp.fc1.bias', 'vit.layers.11.mlp.fc2.weight', 'vit.layers.11.mlp.fc2.bias'].
[transformers] There were unexpected keys in the checkpoint model loaded: ['vit.encoder.layer.0.attention.attention.key.bias', 'vit.encoder.layer.0.attention.attention.key.weight', 'vit.encoder.layer.0.attention.attention.query.bias', 'vit.encoder.layer.0.attention.attention.query.weight', 'vit.encoder.layer.0.attention.attention.value.bias', 'vit.encoder.layer.0.attention.attention.value.weight', 'vit.encoder.layer.0.attention.output.dense.bias', 'vit.encoder.layer.0.attention.output.dense.weight', 'vit.encoder.layer.0.intermediate.dense.bias', 'vit.encoder.layer.0.intermediate.dense.weight', 'vit.encoder.layer.0.layernorm_after.bias', 'vit.encoder.layer.0.layernorm_after.weight', 'vit.encoder.layer.0.layernorm_before.bias', 'vit.encoder.layer.0.layernorm_before.weight', 'vit.encoder.layer.0.output.dense.bias', 'vit.encoder.layer.0.output.dense.weight', 'vit.encoder.layer.1.attention.attention.key.bias', 'vit.encoder.layer.1.attention.attention.key.weight', 'vit.encoder.layer.1.attention.attention.query.bias', 'vit.encoder.layer.1.attention.attention.query.weight', 'vit.encoder.layer.1.attention.attention.value.bias', 'vit.encoder.layer.1.attention.attention.value.weight', 'vit.encoder.layer.1.attention.output.dense.bias', 'vit.encoder.layer.1.attention.output.dense.weight', 'vit.encoder.layer.1.intermediate.dense.bias', 'vit.encoder.layer.1.intermediate.dense.weight', 'vit.encoder.layer.1.layernorm_after.bias', 'vit.encoder.layer.1.layernorm_after.weight', 'vit.encoder.layer.1.layernorm_before.bias', 'vit.encoder.layer.1.layernorm_before.weight', 'vit.encoder.layer.1.output.dense.bias', 'vit.encoder.layer.1.output.dense.weight', 'vit.encoder.layer.10.attention.attention.key.bias', 'vit.encoder.layer.10.attention.attention.key.weight', 'vit.encoder.layer.10.attention.attention.query.bias', 'vit.encoder.layer.10.attention.attention.query.weight', 'vit.encoder.layer.10.attention.attention.value.bias', 'vit.encoder.layer.10.attention.attention.value.weight', 'vit.encoder.layer.10.attention.output.dense.bias', 'vit.encoder.layer.10.attention.output.dense.weight', 'vit.encoder.layer.10.intermediate.dense.bias', 'vit.encoder.layer.10.intermediate.dense.weight', 'vit.encoder.layer.10.layernorm_after.bias', 'vit.encoder.layer.10.layernorm_after.weight', 'vit.encoder.layer.10.layernorm_before.bias', 'vit.encoder.layer.10.layernorm_before.weight', 'vit.encoder.layer.10.output.dense.bias', 'vit.encoder.layer.10.output.dense.weight', 'vit.encoder.layer.11.attention.attention.key.bias', 'vit.encoder.layer.11.attention.attention.key.weight', 'vit.encoder.layer.11.attention.attention.query.bias', 'vit.encoder.layer.11.attention.attention.query.weight', 'vit.encoder.layer.11.attention.attention.value.bias', 'vit.encoder.layer.11.attention.attention.value.weight', 'vit.encoder.layer.11.attention.output.dense.bias', 'vit.encoder.layer.11.attention.output.dense.weight', 'vit.encoder.layer.11.intermediate.dense.bias', 'vit.encoder.layer.11.intermediate.dense.weight', 'vit.encoder.layer.11.layernorm_after.bias', 'vit.encoder.layer.11.layernorm_after.weight', 'vit.encoder.layer.11.layernorm_before.bias', 'vit.encoder.layer.11.layernorm_before.weight', 'vit.encoder.layer.11.output.dense.bias', 'vit.encoder.layer.11.output.dense.weight', 'vit.encoder.layer.2.attention.attention.key.bias', 'vit.encoder.layer.2.attention.attention.key.weight', 'vit.encoder.layer.2.attention.attention.query.bias', 'vit.encoder.layer.2.attention.attention.query.weight', 'vit.encoder.layer.2.attention.attention.value.bias', 'vit.encoder.layer.2.attention.attention.value.weight', 'vit.encoder.layer.2.attention.output.dense.bias', 'vit.encoder.layer.2.attention.output.dense.weight', 'vit.encoder.layer.2.intermediate.dense.bias', 'vit.encoder.layer.2.intermediate.dense.weight', 'vit.encoder.layer.2.layernorm_after.bias', 'vit.encoder.layer.2.layernorm_after.weight', 'vit.encoder.layer.2.layernorm_before.bias', 'vit.encoder.layer.2.layernorm_before.weight', 'vit.encoder.layer.2.output.dense.bias', 'vit.encoder.layer.2.output.dense.weight', 'vit.encoder.layer.3.attention.attention.key.bias', 'vit.encoder.layer.3.attention.attention.key.weight', 'vit.encoder.layer.3.attention.attention.query.bias', 'vit.encoder.layer.3.attention.attention.query.weight', 'vit.encoder.layer.3.attention.attention.value.bias', 'vit.encoder.layer.3.attention.attention.value.weight', 'vit.encoder.layer.3.attention.output.dense.bias', 'vit.encoder.layer.3.attention.output.dense.weight', 'vit.encoder.layer.3.intermediate.dense.bias', 'vit.encoder.layer.3.intermediate.dense.weight', 'vit.encoder.layer.3.layernorm_after.bias', 'vit.encoder.layer.3.layernorm_after.weight', 'vit.encoder.layer.3.layernorm_before.bias', 'vit.encoder.layer.3.layernorm_before.weight', 'vit.encoder.layer.3.output.dense.bias', 'vit.encoder.layer.3.output.dense.weight', 'vit.encoder.layer.4.attention.attention.key.bias', 'vit.encoder.layer.4.attention.attention.key.weight', 'vit.encoder.layer.4.attention.attention.query.bias', 'vit.encoder.layer.4.attention.attention.query.weight', 'vit.encoder.layer.4.attention.attention.value.bias', 'vit.encoder.layer.4.attention.attention.value.weight', 'vit.encoder.layer.4.attention.output.dense.bias', 'vit.encoder.layer.4.attention.output.dense.weight', 'vit.encoder.layer.4.intermediate.dense.bias', 'vit.encoder.layer.4.intermediate.dense.weight', 'vit.encoder.layer.4.layernorm_after.bias', 'vit.encoder.layer.4.layernorm_after.weight', 'vit.encoder.layer.4.layernorm_before.bias', 'vit.encoder.layer.4.layernorm_before.weight', 'vit.encoder.layer.4.output.dense.bias', 'vit.encoder.layer.4.output.dense.weight', 'vit.encoder.layer.5.attention.attention.key.bias', 'vit.encoder.layer.5.attention.attention.key.weight', 'vit.encoder.layer.5.attention.attention.query.bias', 'vit.encoder.layer.5.attention.attention.query.weight', 'vit.encoder.layer.5.attention.attention.value.bias', 'vit.encoder.layer.5.attention.attention.value.weight', 'vit.encoder.layer.5.attention.output.dense.bias', 'vit.encoder.layer.5.attention.output.dense.weight', 'vit.encoder.layer.5.intermediate.dense.bias', 'vit.encoder.layer.5.intermediate.dense.weight', 'vit.encoder.layer.5.layernorm_after.bias', 'vit.encoder.layer.5.layernorm_after.weight', 'vit.encoder.layer.5.layernorm_before.bias', 'vit.encoder.layer.5.layernorm_before.weight', 'vit.encoder.layer.5.output.dense.bias', 'vit.encoder.layer.5.output.dense.weight', 'vit.encoder.layer.6.attention.attention.key.bias', 'vit.encoder.layer.6.attention.attention.key.weight', 'vit.encoder.layer.6.attention.attention.query.bias', 'vit.encoder.layer.6.attention.attention.query.weight', 'vit.encoder.layer.6.attention.attention.value.bias', 'vit.encoder.layer.6.attention.attention.value.weight', 'vit.encoder.layer.6.attention.output.dense.bias', 'vit.encoder.layer.6.attention.output.dense.weight', 'vit.encoder.layer.6.intermediate.dense.bias', 'vit.encoder.layer.6.intermediate.dense.weight', 'vit.encoder.layer.6.layernorm_after.bias', 'vit.encoder.layer.6.layernorm_after.weight', 'vit.encoder.layer.6.layernorm_before.bias', 'vit.encoder.layer.6.layernorm_before.weight', 'vit.encoder.layer.6.output.dense.bias', 'vit.encoder.layer.6.output.dense.weight', 'vit.encoder.layer.7.attention.attention.key.bias', 'vit.encoder.layer.7.attention.attention.key.weight', 'vit.encoder.layer.7.attention.attention.query.bias', 'vit.encoder.layer.7.attention.attention.query.weight', 'vit.encoder.layer.7.attention.attention.value.bias', 'vit.encoder.layer.7.attention.attention.value.weight', 'vit.encoder.layer.7.attention.output.dense.bias', 'vit.encoder.layer.7.attention.output.dense.weight', 'vit.encoder.layer.7.intermediate.dense.bias', 'vit.encoder.layer.7.intermediate.dense.weight', 'vit.encoder.layer.7.layernorm_after.bias', 'vit.encoder.layer.7.layernorm_after.weight', 'vit.encoder.layer.7.layernorm_before.bias', 'vit.encoder.layer.7.layernorm_before.weight', 'vit.encoder.layer.7.output.dense.bias', 'vit.encoder.layer.7.output.dense.weight', 'vit.encoder.layer.8.attention.attention.key.bias', 'vit.encoder.layer.8.attention.attention.key.weight', 'vit.encoder.layer.8.attention.attention.query.bias', 'vit.encoder.layer.8.attention.attention.query.weight', 'vit.encoder.layer.8.attention.attention.value.bias', 'vit.encoder.layer.8.attention.attention.value.weight', 'vit.encoder.layer.8.attention.output.dense.bias', 'vit.encoder.layer.8.attention.output.dense.weight', 'vit.encoder.layer.8.intermediate.dense.bias', 'vit.encoder.layer.8.intermediate.dense.weight', 'vit.encoder.layer.8.layernorm_after.bias', 'vit.encoder.layer.8.layernorm_after.weight', 'vit.encoder.layer.8.layernorm_before.bias', 'vit.encoder.layer.8.layernorm_before.weight', 'vit.encoder.layer.8.output.dense.bias', 'vit.encoder.layer.8.output.dense.weight', 'vit.encoder.layer.9.attention.attention.key.bias', 'vit.encoder.layer.9.attention.attention.key.weight', 'vit.encoder.layer.9.attention.attention.query.bias', 'vit.encoder.layer.9.attention.attention.query.weight', 'vit.encoder.layer.9.attention.attention.value.bias', 'vit.encoder.layer.9.attention.attention.value.weight', 'vit.encoder.layer.9.attention.output.dense.bias', 'vit.encoder.layer.9.attention.output.dense.weight', 'vit.encoder.layer.9.intermediate.dense.bias', 'vit.encoder.layer.9.intermediate.dense.weight', 'vit.encoder.layer.9.layernorm_after.bias', 'vit.encoder.layer.9.layernorm_after.weight', 'vit.encoder.layer.9.layernorm_before.bias', 'vit.encoder.layer.9.layernorm_before.weight', 'vit.encoder.layer.9.output.dense.bias', 'vit.encoder.layer.9.output.dense.weight'].

מעריך ביצועים על נתוני הבדיקה...

דיוק סופי: 0.9983
מושך את המפתח מתוך קולאב ומבצע התחברות ל-Hugging Face...
שומר את המודל מקומית בנתיב: ./tomadoc_advanced_ripeness_model

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

מעלה את כל הקבצים למאגר הענן: tomadoc-advanced-ripeness-classifier

RepositoryNotFoundError: 404 Client Error. (Request ID: Root=1-6a2b0d86-69ad5d836ec0c8263e89e4c3;94d9536c-8dea-44bb-912c-b16146c19a26)

Repository Not Found for url: https://huggingface.co/api/models/tomadoc-advanced-ripeness-classifier/preupload/main.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated and your token has the required permissions.
For more details, see https://huggingface.co/docs/huggingface_hub/authentication
Note: Creating a commit assumes that the repo already exists on the Huggingface Hub. Please use `create_repo` if it's not the case.

In [3]:
print("מושך את המפתח מתוך קולאב ומבצע התחברות ל-Hugging Face...")
hf_token = userdata.get('HF_TOKEN')
login(token=hf_token)

local_directory = "./tomadoc_advanced_ripeness_model"
hf_repository_name = "oshriagronov/tomadoc-flash"

print(f"שומר את המודל מקומית בנתיב: {local_directory}")
trainer.save_model(local_directory)
processor.save_pretrained(local_directory)

model_card_content = f"""---
language:
- en
license: mit
tags:
- image-classification
- vit
- agriculture
- tomato-ripeness
- freshcheck
metrics:
- accuracy
pipeline_tag: image-classification
---

# Tomadoc Advanced Tomato Ripeness Classifier

This model is a fine-tuned version of `google/vit-base-patch16-224` designed to identify the exact ripening stage of a tomato. It was trained on the extensive FreshCheck dataset to provide highly accurate agricultural insights for the Tomadoc application.

## Model Description
- **Model Type:** Vision Transformer (ViT)
- **Task:** Image Classification
- **Classes:** Unripe, Ripe, Overripe, Damaged
- **Base Model:** google/vit-base-patch16-224

## Training & Hardware Details
- **Dataset:** FreshCheck Fruit Ripeness Classification Dataset
- **Hardware Used:** NVIDIA T4 GPU
- **Precision:** Mixed Precision (FP16)
- **Evaluation Strategy:** Epoch-based
- **Learning Rate:** 2e-5
- **Epochs:** 5

## Evaluation Results
- **Final Test Accuracy:** {accuracy_score:.4f}
"""

readme_path = os.path.join(local_directory, "README.md")
with open(readme_path, "w", encoding="utf-8") as f:
    f.write(model_card_content)

api = HfApi()
api.create_repo(repo_id=hf_repository_name, exist_ok=True)

print(f"מעלה את כל הקבצים למאגר הענן: {hf_repository_name}")
api.upload_folder(
    folder_path=local_directory,
    repo_id=hf_repository_name,
    commit_message="Upload advanced Tomadoc ripeness model"
)

print("התהליך הושלם בהצלחה.")

מושך את המפתח מתוך קולאב ומבצע התחברות ל-Hugging Face...
שומר את המודל מקומית בנתיב: ./tomadoc_advanced_ripeness_model

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

מעלה את כל הקבצים למאגר הענן: oshriagronov/tomadoc-flash

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...s_model/model.safetensors:   0%|          |  553kB /  343MB

  ...s_model/training_args.bin:  48%|####8     | 2.52kB / 5.20kB

התהליך הושלם בהצלחה.